config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users
  root to: "pages#main"
  get "/about", to: "pages#about", as: "about"
  get "/contact", to: "pages#contact", as: "contact"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  post "/show/:id/buy", to: "products#buy", as: "buy"
  get "/show/:id/success", to: "products#success", as: "success"
  get "/show/:id/cancel", to: "products#cancel", as: "cancel"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    has_one_attached :image, dependent: :purge
    #The below lines of code validate the entry of data and attempt to prevent intrusive data entry
    validates :name, :image, presence: true
    validates :name, uniqueness: true
    validates :price, numericality: {greater_than_or_equal_to: 10}
end

app/models/roles.rb
class Roles < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, dependent: :destroy
  rolify :role_cname => 'Roles'
  after_create :assign_default_role
  validates :email, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
         
  def assign_default_role
    self.add_role(:buyer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #Using the time shows to me that the website is still updating and nothing has broken
  def main
  @time = Time.now
  end

  def about
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:buy]
  before_action :set_product, only: [:show, :edit, :update, :destroy, :buy]
  before_action :authenticate_user!
  rescue_from ActiveModel::RangeError, with: :invalidity
  rescue_from ActiveRecord::RecordNotFound, with: :invalidity
  # before_action :check_roles
  

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end
  
  def buy
    Stripe.api_key = ENV['STRIPE_API_KEY']
    session = Stripe::Checkout::Session.create({
      payment_method_types: ['card'],
      mode: 'payment',
      success_url: success_url(params[:id]),
      cancel_url: cancel_url(params[:id]),
      line_items: [
        {
          price_data: {
            currency: 'aud',
            product_data: {
              name: @product.name
            },
            unit_amount: (@product.price * 100).to_i
          },
          quantity: 1
        }
      ]
    })

    render json: session
  end
  #If a user purchases an item it renders a success message
  def success
  end
  #If a user cancels their order it returns them to the home page
  def cancel
    redirect_to root_path
  end
  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end
#Prevents entering malicious number of integers
    def invalidity
      logger.error "Attempted an invalid action"
      redirect_to root_path, notice: "Invalid Data Entry"
    end
    # def check_roles
    #   if !current_user.has_role?(:admin)
    #     flash[:alert] = "You aren't allowed to be here you cheeky devil!"
    #     redirect_to root_path
    #   end
    # end


    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OatsRiceVeg</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous" defer></script>
  
    </head>
  <nav>
  <%= link_to "Our Story", "/about" %>
  <%= link_to "Get in touch", "/contact" %>
  <%= link_to "Homepage", "/" %>

  </nav>
  <body>
    <main class='<%=controller.controller_name %>'>
    <%= yield %>
    </main>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if user_signed_in? %>
      <h4> 
      Welcome, <%= current_user.email %>!
      || <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      </h4>
      <% else %>
      <h4>
      Welcome!
      <%= link_to 'Login', user_session_path, method: :post %>
      <%= link_to 'Register', new_user_registration_path, method: :get %>
      </h4>
    <% end %>
    <% yield %>
  </body>
</html>

app/views/pages/about.html.erb
<p> insert picture of us with our Donabe! </p>

app/views/pages/contact.html.erb
<p> We hope if you need us we're just a moment away, reach us at test@gmail.com </p>

app/views/pages/main.html.erb
<h1>Oats Rice and Veg</h1>

<p>
Thanks for coming to Oats, Rice and Veg the time is <%= @time %>!
<p> Ebby and Sam are so excited to show you a new way to cook healthy. <3 </p>
<%= link_to "Take me to the Donabe's!", "/products" %>
</p>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<h1>The Collection</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr class= "<%= cycle('list_line_odd', 'list_line_even') %>">
        <td><%= product.name %></td>
        <td><%= number_to_currency(product.price) %></td>
         <td><%= cl_image_tag(product.image.key, cloud_name: "dpwztry10", :width=>300, :crop=>"scale") %></td>
        <% if user_signed_in? && current_user.has_role?(:admin) %>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
          <td><%= link_to 'Show', product %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%# <%= @product%>
  <%= cl_image_tag(@product.image.key, cloud_name: "dpwztry10", :width=>300, :crop=>"scale") %>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@product.price) %>
</p>
<% if user_signed_in? && current_user != @product.user %>
  <p><button id="buynow-button">Buy Now!</button></p>
<% end %>
<% if user_signed_in? && (current_user.id == @product.user_id or current_user.has_role?(:admin)) %>
  <%= link_to 'Edit', edit_product_path(@product) %>
<% end %>
  <%= link_to 'Back', products_path %>
<script src="https://js.stripe.com/v3/"></script>

<script>
  const stripe = Stripe('<%= ENV["STRIPE_PUBLISHABLE_KEY"] %>')
  const buyButton = document.getElementById('buynow-button')

  buyButton.addEventListener('click', function() {
      fetch('<%= buy_path(@product.id) %>', { 
          method: 'POST'
      })
      .then(function(response) {
          return response.json()
      })
      .then(function(session) {
          return stripe.redirectToCheckout({ sessionId: session.id })
      })
  })
</script>

app/views/products/success.html.erb
<h1> Your order has been placed successfully! </h1>